name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Restore cached dependencies
      uses: actions/cache@v1
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package.json') }}
    - name: Install dependencies
      run: npm ci

    - name: build storybook
      run: npm run build-storybook

    - name: deploy github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./storybook-static